class config:
    bread_cal = {'Honey_Oat':230, 
                'Hearty_Italian':210, 
                'Wheat':210, 
                'Parmesan_Oregano':210, 
                'White':200,
                'Flat_Bread':230}
    sauce_cal = {'Ranch': 110,
                 'Mayonnaise' : 110,
                 'Sweet_Onion': 40,
                 'Honey_Mustard': 30,
                 'Sweet_Chilli': 30,
                 'Hot_Chilli': 40,
                 'Southwest_Chipotle': 100,
                 'Horseradish': 110,
                 'Yellow_Mustard': 5,
                 'Italian_Dressing': 80,
                 'Olive_Oil': 45,
                 'Red_Wine_Vinaigrette': 40,
                 'Salt': 0,
                 'Black_Pepper': 0,
                 'Thousand_Island': 80,
                 'Smoke_BBQ': 35}
    sandwich_cal = {
                    'Egg_Mayo_sandwich':480,
                    'Ham_sandwich':290,
                    'Tuna_sandwich':480,
                    'Meatball_sandwich':480,
                    'BLT_sandwich':380,
                    'Italian_BMT_sandwich':410,
                    'Veggie_Delite_sandwich':230,
                    'Turkey_sandwich':280,
                    'Subway_Club_sandwich':310,
                    'Roasted_Beef_sandwich':320,
                    'Rotisserie_Chicken_sandwich':350,
                    'Roasted_Chicken_sandwich':320,
                    'Chicken_Teriyaki_sandwich':370,
                    'Turkey_Bacon_sandwich':348,
                    'Spicy_Italian_sandwich':480,
                    'Chicken_Bacon_Ranch_sandwich':610,
                    'Subway_Melt_sandwich':365,
                    'Pulled_Pork_sandwich':420,
                    'Steak_And_Cheese_sandwich':380,
                    'Turkey_Bacon_Avocado_sandwich':420}
    
    cheese_cal={'American':40,
                    'Shredded':50,
                    'Mozzarella':44}
    
    Main_topping_cal={'Egg_mayo':80,
                    'Ham':40,
                    'Tuna':40,
                     'Meatball':42,
                     'Bacon':60,
                     'Salami':64,
                     'Rotisserie_chicken':110,
                     'Roasted_chicken':90,
                     'Chicken_teriyaki':170,
                     'Pepperoni':72,
                     'Roasted_beef':150,
                     'Chicken_strip':150,
                     'Pulled_Pork':150,
                     'Steak':150,
                     'Omelet':85,
                     'Turkey':48,
                     'Avocado':40}
    
    sub_topping_cal = {'Olives':5,
                'Cucumbers':5,
                'Sweet_Peppers':5,
                 'Lettuce':5,
                 'Pickle':5,
                 'Tomatoes':5,
                 'jalapeno':5,
                 'Onions':5}
    
    Extra_topping_cost={'Egg_mayo':1500,
                    'Ham':1500,
                    'Tuna':1500,
                     'Meatball':1500,
                     'Bacon':1500,
                     'Salami':1500,
                     'Rotisserie_chicken':1500,
                     'Roasted_chicken':1500,
                     'Chicken_teriyaki':1500,
                     'Pepperoni':1500,
                     'Roasted_beef':1500,
                     'Chicken_strip':1500,
                     'Pulled_Pork':1500,
                     'Steak':1500,
                     'Omelet':1100,
                     'Turkey':1500,
                     'Avocado':1100}
      
    Sandwich_cost={'Egg_Mayo_sandwich':4300, 
               'Ham_sandwich':4700, 
               'Tuna_sandwich':4800, 
               'Meatball_sandwich':4900, 
               'BLT_sandwich':5100,
               'Italian_BMT_sandwich':5100,
               'Veggie_Delite_sandwich':3900, 
               'Turkey_sandwich':5100, 
               'Subway_Club_sandwich':5600, 
               'Roasted_Beef_sandwich':5900, 
               'Rotisserie_Chicken_sandwich':5900,
               'Roasted_Chicken_sandwich':5900,
               'Chicken_Teriyaki_sandwich':5600, 
               'Turkey_Bacon_sandwich':5600, 
               'Spicy_Italian_sandwich':5600, 
               'Chicken_Bacon_Ranch_sandwich':5900, 
               'Subway_Melt_sandwich':5900,
               'Pulled_Pork_sandwich':5900,
               'Steak_And_Cheese_sandwich':6300,
               'Turkey_Bacon_Avocado_sandwich':6300}